language: python
python:
 
  - "3.6"      # current default Python on Travis CI
  # for some reason travis breaks here
  #- "3.7"
    #env: TEST_TYPE="quandl" PANDAS=1 NUMPY=1.19
  - "3.8"
  - "3.8-dev" 
  - "3.9"
  - "3.9-dev" 

# command to install dependencies
install:
  - pip install -r software_module/requirements.txt
  - pip install software_module/.
# command to run tests
script:
  - pytest
